disabled_rules:
    - trailing_whitespace
    - force_cast
    - line_length
    - function_body_length
    - type_body_length
identifier_name:
    allowed_symbols: "_"
type_name:
    allowed_symbols: "_"
opt_in_rules:
    - empty_string
excluded:
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib
function_parameter_count:
    warning: 6
    error: 8
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
